### ISSUE TITLE
apiKeyService.generate not returning error when invalid password is given to create the apiKeyService

### ISSUE THREAD

**Issue by barberdt** [buglabs/bugswarm-nodejs#2]
**Note:** This error is only occurring on the test server. Locally, everything works fine. The code both on the app-side and the library side are identical between servers.

When using the management app to replace API keys, if an invalid password is given, it is expected that the call to apiKeyService.generate will give an 'Authorization Required' due to the fact that an invalid password was used to create the apiKeyService instance. This successfully happens on my local server. However, on the test server, no error is returned by the call to apiKeyService.generate. Instead, 'err' is undefined, so the management app acts as if there was no error, even though an invalid password was given. I have tailed the logs on the test server to confirm that 'err' is undefined.

**Comment by c4milo** [comment]
I know what it is. Although, we can workaround by patching the nodejs library, I think I am going to fix the real issue in the platform.

**Comment by c4milo** [comment]
Closed along with buglabs/bugswarm#91
